# Generated by Django 5.2.7 on 2025-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_image_message_voice_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='waveform',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
