# Generated by Django 5.2.7 on 2025-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_delivered_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbs/'),
        ),
    ]
