# Generated by Django 5.2.7 on 2025-12-06 10:20

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_video_message_video_duration_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_message_media),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.upload_message_media),
        ),
    ]
