# Generated by Django 5.2.7 on 2025-12-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_video_alter_message_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='video_duration_ms',
            new_name='video_duration',
        ),
    ]
